name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Expo CLI and EAS CLI
      run: |
        echo "instalando dependencies"
        npm i
        echo "instalando dependencies2"
        npm install -g expo-cli@latest
        npm install -g eas-cli@latest

    - name: Build APK
      run: |
        eas build --platform android --non-interactive
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  
