name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Expo CLI and EAS CLI
      run: |
        npm install
        npm install -g expo-cli@latest
        npm install -g eas-cli@latest

    - name: Build APK
      id: build
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      run: |
        echo "Starting the build process"
        # Run the build command and capture its output
        OUTPUT=$(eas build --platform android --non-interactive)
        echo "$OUTPUT"
        # Extract the build URL from the build output
        BUILD_URL=$(echo "$OUTPUT" | grep -oP '(?<=🤖 Android app:\n).+')
        echo "BUILD_URL=$BUILD_URL" >> $GITHUB_ENV

    - name: Download APK
      if: env.BUILD_URL
      run: |
        echo "Downloading APK from $BUILD_URL"
        curl -L -o app-release.apk ${{ env.BUILD_URL }}

    - name: Upload APK as artifact
      if: env.BUILD_URL
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: app-release.apk
